# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-11-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('desc', models.TextField(max_length=255, verbose_name='项目描述')),
                ('start_time', models.DateField(verbose_name='项目开始时间')),
                ('end_time', models.DateField(verbose_name='项目结束时间')),
            ],
        ),
    ]
