# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-11-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_report', models.TextField(default='', verbose_name='报告')),
                ('log_run_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='log日志产生时间')),
                ('log_pass_count', models.IntegerField(verbose_name='通过数量')),
                ('log_failed_count', models.IntegerField(verbose_name='失败数量')),
                ('log_errors_count', models.IntegerField(verbose_name='报错数量')),
                ('log_run_count', models.IntegerField(verbose_name='执行用例总数')),
                ('log_sub_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.It', verbose_name='所属接口项目')),
            ],
            options={
                'ordering': ['-log_run_time'],
            },
        ),
        migrations.AlterField(
            model_name='api',
            name='api_desc',
            field=models.TextField(default='', max_length=255, verbose_name='用例描述'),
        ),
    ]
